### ISSUE TITLE
restclient: turn {{url}} into :url etc.

### ISSUE THREAD

**Issue by unhammer** [flashcode/impostman#1]
Postman environment variables don't seem to be converted. 

(Maybe it'd also be nice to be able to import the environment files that define these, or at least put some initialising placeholders at the top of the import for each such, e.g. if `{{url}}`  is seen at least once, then put `:url = "TODO"` at the top of the result).

**Comment by flashcode** [comment]
Yes, nice idea.

I know we can use such variables in URLs in Postman, do you know if they can be used elsewhere?
Just to be sure to cover all cases.

And I'll check to add similar variables in verb output.

**Comment by flashcode** [comment]
Nevermind, I'll read the Postman docs and do it accordingly.

**Comment by flashcode** [comment]
Done!

The Postman environment with variables can now be imported with the collection.
So if you're using variables, you must give the environment file (even if it is optional), otherwise variables will not be initialized in output.

A new option `impostman-use-variables` has been added to control whether variables are used (enabled by defaut).
If set to nil, variables are directly replaced by their values (or the variable name itself if the value is unknown).

Both `verb` and `restclient` have support for variables, with different syntaxes.
For examples, see files `verb.org` and `restclient.org` in `tests` directory.
